from typing import Dict, List, Optional, Tuple

class VividError(OSError): ...
class ClosedHandleError(VividError): ...

class Session:
    @property
    def closed(self) -> bool: ...

class Source:
    @property
    def id(self) -> int: ...
    @property
    def kind(self) -> str: ...
    @property
    def closed(self) -> bool: ...

class MediaSender:
    @property
    def id(self) -> int: ...
    @property
    def kind(self) -> str: ...
    @property
    def closed(self) -> bool: ...

class Wait:
    @property
    def request_id(self) -> int: ...
    @property
    def source_id(self) -> int: ...
    @property
    def closed(self) -> bool: ...

EventTuple = Tuple[str, Optional[bool], Optional[int], Optional[str]]

def connect(
    endpoint: Optional[str],
    bulk_endpoint: Optional[str],
    token: Optional[str],
    dry_run: bool,
    trace_dir: Optional[str],
    verbose: bool,
    producer: str,
    producer_version: str,
    required_features: List[int],
    optional_features: List[int],
) -> Session: ...
def close(session: Session) -> None: ...
def allocate_id(session: Session) -> int: ...
def supports(session: Session, feature: int) -> bool: ...
def root_context_id(session: Session) -> int: ...
def display_state(session: Session) -> Tuple[int, int, int, int, int, int, int, bool]: ...
def revision_state(session: Session) -> Tuple[int, List[Tuple[int, int]]]: ...
def set_observation(session: Session, class_mask: int) -> None: ...
def take_observation(
    session: Session,
) -> Optional[
    Tuple[
        str,
        Optional[int],
        int,
        int,
        int,
        Optional[int],
        Optional[Tuple[int, int, int, int, int, int, int]],
    ]
]: ...
def query_source(session: Session, source_id: int) -> Dict[str, object]: ...
def query_scene(
    session: Session,
    maximum_nodes_per_page: int = 256,
    maximum_pages: int = 16,
) -> Dict[str, object]: ...
def query_anchor(session: Session, anchor_id: int) -> Tuple[int, int, int, int, bool, int]: ...
def query_limits(session: Session) -> Dict[str, object]: ...
def begin_wait_source(
    session: Session,
    source_id: int,
    condition: int,
    value: Optional[int],
    timeout: float,
) -> Wait: ...
def wait_source(wait: Wait) -> Tuple[int, int, int, Optional[int]]: ...
def cancel_wait(wait: Wait) -> None: ...
def wait_until_playing(
    session: Session, source_id: int, timeout: float
) -> Tuple[int, int, int, Optional[int]]: ...
def play_and_wait_until_playing(
    session: Session,
    source_id: int,
    start_pts_us: int,
    minimum_buffer_us: int,
    timeout: float,
) -> Tuple[int, int, int, Optional[int]]: ...
def create_text_anchor(session: Session) -> Optional[int]: ...
def create_raster_source(
    session: Session, source_id: int, width: int, height: int,
    preconditions: Optional[Dict[int, int]] = ...,
    idempotency_key: Optional[bytes] = ..., causation_id: Optional[bytes] = ...
) -> Source: ...
def create_image_source(
    session: Session,
    source_id: int,
    encoding: int,
    width: int,
    height: int,
    encoded_length: int,
    sha256: Optional[bytes],
    preconditions: Optional[Dict[int, int]] = ...,
    idempotency_key: Optional[bytes] = ...,
    causation_id: Optional[bytes] = ...,
) -> Source: ...
def create_video_source(
    session: Session, source_id: int, config: Dict[str, object],
    preconditions: Optional[Dict[int, int]] = ...,
    idempotency_key: Optional[bytes] = ..., causation_id: Optional[bytes] = ...
) -> Source: ...
def create_audio_source(
    session: Session,
    source_id: int,
    linked_video_source_id: Optional[int],
    config: Dict[str, object],
    preconditions: Optional[Dict[int, int]] = ...,
    idempotency_key: Optional[bytes] = ...,
    causation_id: Optional[bytes] = ...,
) -> Source: ...
def create_linked_av_sources(
    session: Session,
    video_source_id: int,
    video_config: Dict[str, object],
    audio_source_id: int,
    audio_config: Dict[str, object],
) -> Tuple[Source, Optional[Source], Optional[str]]: ...
def probe_video_config(session: Session, config: Dict[str, object]) -> bool: ...
def probe_audio_config(session: Session, config: Dict[str, object]) -> bool: ...
def place_source(
    session: Session,
    source_id: int,
    node_id: int,
    anchor_id: Optional[int],
    columns: int,
    rows: int,
) -> None: ...
def create_scene_node(session: Session, config: Dict[str, object]) -> Tuple[int, int]: ...
def update_scene_node(session: Session, config: Dict[str, object]) -> Tuple[int, int]: ...
def delete_scene_node(session: Session, node_id: int) -> None: ...
def destroy_source(
    session: Session, source_id: int,
    preconditions: Optional[Dict[int, int]] = ...,
    idempotency_key: Optional[bytes] = ..., causation_id: Optional[bytes] = ...
) -> None: ...
def wait_until_visible(session: Session, source: Source) -> None: ...
def check_source(session: Session, source: Source) -> None: ...
def take_source_event(source: Source) -> Optional[EventTuple]: ...
def source_is_visible(source: Source) -> bool: ...
def source_visibility_reasons(source: Source) -> int: ...
def open_sender(session: Session, source: Source) -> MediaSender: ...
def send_raster(
    sender: MediaSender,
    epoch: int,
    frame_id: int,
    width: int,
    height: int,
    rgba: bytes,
) -> None: ...
def send_image(sender: MediaSender, encoded: bytes) -> None: ...
def send_video(
    sender: MediaSender,
    epoch: int,
    packet_id: int,
    pts_us: int,
    dts_us: int,
    duration_us: int,
    key: bool,
    data: bytes,
) -> None: ...
def send_audio(
    sender: MediaSender,
    epoch: int,
    packet_id: int,
    pts_us: int,
    dts_us: int,
    duration_us: int,
    trim_start_samples: int,
    trim_end_samples: int,
    data: bytes,
) -> None: ...
def cancel_sender(sender: MediaSender, reason: str) -> None: ...
def take_sender_event(sender: MediaSender) -> Optional[EventTuple]: ...
def sender_is_visible(sender: MediaSender) -> bool: ...
def sender_visibility_reasons(sender: MediaSender) -> int: ...
def play(
    session: Session,
    source_id: int,
    start_pts_us: int,
    minimum_buffer_us: int,
    preconditions: Optional[Dict[int, int]] = ...,
    idempotency_key: Optional[bytes] = ...,
    causation_id: Optional[bytes] = ...,
) -> None: ...
def pause(
    session: Session, source_id: int, preconditions: Optional[Dict[int, int]] = ...,
    idempotency_key: Optional[bytes] = ..., causation_id: Optional[bytes] = ...
) -> None: ...
def flush(
    session: Session, source_id: int, epoch: int,
    preconditions: Optional[Dict[int, int]] = ...,
    idempotency_key: Optional[bytes] = ..., causation_id: Optional[bytes] = ...
) -> None: ...
def eos(
    session: Session, source_id: int, epoch: int,
    preconditions: Optional[Dict[int, int]] = ...,
    idempotency_key: Optional[bytes] = ..., causation_id: Optional[bytes] = ...
) -> None: ...
def drain(session: Session, source_id: int, timeout_seconds: Optional[float]) -> None: ...
