"""Stub for the compiled extension.

Every function here marshals to and from `vivid_sdk`; none of them decide protocol values, so
this file describes shapes rather than rules. Dictionaries carry the integer-keyed payloads the
wire uses, re-encoded as bytes where a value is not a scalar the host can read directly.
"""

from typing import Any, Dict, List, Optional, Sequence, Tuple, Union

BytesLike = Union[bytes, bytearray, memoryview]
Payload = Dict[int, Any]
Config = Dict[str, Any]

class VividError(OSError): ...
class ClosedHandleError(VividError): ...

class OverlayStyledText:
    def __init__(self, canvas: OverlayCanvas, decorations: list[int], max_width: Optional[float], alignment: str, wrap: bool, max_lines: Optional[int]) -> None: ...

class OverlayTextLayout:
    def measurement(self) -> dict[str, Any]: ...

class OverlayCanvas:
    def __init__(self) -> None: ...
    def snapshot(self) -> OverlayCanvas: ...
    @staticmethod
    def shape(kind: str, bounds: Sequence[float], radius: float) -> List[List[float]]: ...
    def draw(self, segments: Sequence[Sequence[float]], even_odd: bool, kind: str, geometry: Sequence[float], colors: Sequence[float], offsets: Sequence[float], width: Optional[float]) -> None: ...
    def state(self, kind: str, values: Sequence[float]) -> None: ...
    def clip(self, segments: Sequence[Sequence[float]], even_odd: bool) -> None: ...
    def text(self, text: str, x: float, y: float, size: float, color: int, family: str, weight: int, italic: bool, max_width: Optional[float]) -> None: ...
    def hit(self, segments: Sequence[Sequence[float]], even_odd: bool, id: int, role: str, edges: float) -> None: ...
    def validate(self) -> None: ...

class OverlaySession:
    @staticmethod
    def adopt(session: Session) -> OverlaySession: ...
    def create_window(self, bounds: Sequence[float], mode: str, title: str, visible: bool, parent: Optional[OverlayWindow]) -> OverlayWindow: ...
    def capture_pointer(self, window: OverlayWindow, capture: bool) -> None: ...
    def wait_event(self, timeout: float) -> Optional[OverlayEvent]: ...
    def close(self) -> None: ...

class OverlayWindow:
    def text_batch(self, texts: list[OverlayStyledText], retain: bool) -> list[OverlayTextLayout]: ...
    def draw_text_layout(self, canvas: OverlayCanvas, layout: OverlayTextLayout, x: float, y: float) -> None: ...
    def release_text_layout(self, layout: OverlayTextLayout) -> None: ...
    def measure_text(self, canvas: OverlayCanvas) -> Dict[str, Any]: ...
    def set_editor_geometry(self, scene_revision: int, caret: Optional[Sequence[float]]) -> None: ...
    def present(self, canvas: OverlayCanvas) -> None: ...
    def set_bounds(self, bounds: Sequence[float]) -> None: ...
    def set_visible(self, visible: bool) -> None: ...
    def action(self, action: str) -> None: ...
    def bounds(self) -> List[float]: ...
    def viewport(self) -> Tuple[float, float, int, int]: ...
    def upload_rgba(self, width: int, height: int, rgba: bytes) -> OverlayImage: ...
    def draw_image(self, canvas: OverlayCanvas, image: OverlayImage, bounds: Sequence[float], opacity: float) -> None: ...

class OverlayImage: ...
class OverlayEvent:
    def targets(self, window: OverlayWindow) -> bool: ...
    def data(self) -> Dict[str, Any]: ...

class Session:
    @property
    def closed(self) -> bool: ...

class Surface:
    @property
    def context_id(self) -> int: ...
    @property
    def id(self) -> int: ...
    @property
    def revision(self) -> int: ...
    @property
    def generation(self) -> int: ...

class Track:
    @property
    def context_id(self) -> int: ...
    @property
    def surface_id(self) -> int: ...
    @property
    def id(self) -> int: ...
    @property
    def kind(self) -> str: ...
    @property
    def revision(self) -> int: ...
    @property
    def channel_generation(self) -> int: ...

class TrackChannel:
    @property
    def context_id(self) -> int: ...
    @property
    def surface_id(self) -> int: ...
    @property
    def track_id(self) -> int: ...
    @property
    def kind(self) -> str: ...
    @property
    def generation(self) -> int: ...
    @property
    def closed(self) -> bool: ...

class TrackSender:
    @property
    def generation(self) -> int: ...
    @property
    def detached(self) -> bool: ...
    def next_packet_id(self) -> int: ...
    def current_epoch(self) -> int: ...
    def bump_epoch(self) -> int: ...

class VideoRateControl:
    def __init__(self, configured_bits_per_second: int) -> None: ...
    def observe_send(self, bytes: int, pressure: Config) -> None: ...
    def observe_audio_backlog(self, backlog_us: int) -> None: ...
    def poll(self) -> Optional[int]: ...
    def snapshot(self) -> Dict[str, int]: ...

class InputLane:
    @property
    def generation(self) -> int: ...
    @property
    def closed(self) -> bool: ...

class IncomingFileTransfer:
    @property
    def closed(self) -> bool: ...

class PaneSession:
    @staticmethod
    def from_env() -> "PaneSession": ...
    @staticmethod
    def from_session(session: Session) -> "PaneSession": ...
    @property
    def closed(self) -> bool: ...
    @property
    def has_presentation(self) -> bool: ...

class DesktopSession:
    @property
    def closed(self) -> bool: ...

class Presenter:
    @property
    def closed(self) -> bool: ...
    @property
    def endpoint(self) -> str: ...

def constant_table() -> List[Tuple[str, Optional[str], Optional[int]]]: ...
def probe_encoded_image(data: BytesLike) -> Tuple[int, int, int, int]: ...

def connect(**options: Any) -> Session: ...
def close(session: Session) -> None: ...
def abort(session: Session) -> None: ...
def allocate_id(session: Session) -> int: ...
def supports(session: Session, profile: str) -> bool: ...
def session_info(session: Session) -> Dict[str, Any]: ...
def take_event(session: Session) -> Optional[Dict[str, Any]]: ...
def wait_event(session: Session, *, timeout_us: int = ...) -> Optional[Dict[str, Any]]: ...

def build_surface_config(session: Session, config: Config) -> Config: ...
def build_track_config(session: Session, surface: Config, config: Config) -> Config: ...

def create_surface(session: Session, config: Config) -> Surface: ...
def update_surface(session: Session, surface: Surface, config: Config) -> None: ...
def destroy_surface(session: Session, surface: Surface) -> None: ...
def query_surface(session: Session, surface: Surface) -> Dict[str, Any]: ...

def create_track(session: Session, config: Config) -> Track: ...
def destroy_track(session: Session, track: Track) -> None: ...
def query_track(session: Session, track: Track) -> Dict[str, Any]: ...
def probe_track(session: Session, surface: Surface, config: Config) -> Dict[str, Any]: ...
def open_track_channel(session: Session, track: Track) -> TrackChannel: ...
def close_channel(channel: TrackChannel) -> None: ...
def advance_channel(session: Session, track: Track, reason: int) -> TrackChannel: ...

def send_raster(
    channel: TrackChannel,
    rgba: BytesLike,
    *,
    epoch: int = ...,
    frame_id: int = ...,
    compress: bool = ...,
) -> int: ...
def send_raster_adaptive(
    channel: TrackChannel, rgba: BytesLike, *, epoch: int = ..., frame_id: int = ...
) -> int: ...
def send_raster_delta(
    channel: TrackChannel, operations: Sequence[Config], **options: Any
) -> int: ...
def send_raster_delta_adaptive(
    channel: TrackChannel, operations: Sequence[Config], **options: Any
) -> int: ...
def send_image(channel: TrackChannel, encoded: BytesLike) -> int: ...
def send_video(channel: TrackChannel, data: BytesLike, **options: Any) -> int: ...
def send_audio(channel: TrackChannel, data: BytesLike, **options: Any) -> int: ...
def channel_eos(channel: TrackChannel) -> int: ...
def channel_take_event(channel: TrackChannel) -> Optional[Dict[str, Any]]: ...
def channel_wait_event(
    channel: TrackChannel, *, timeout_us: int = ...
) -> Optional[Dict[str, Any]]: ...
def take_send_pressure(channel: TrackChannel) -> Dict[str, int]: ...
def media_credit_available(channel: TrackChannel, body_length: int) -> bool: ...
def grant_audio_input(channel: TrackChannel) -> None: ...
def take_audio_input(channel: TrackChannel) -> Optional[Dict[str, Any]]: ...

def sender_send_video(sender: TrackSender, data: BytesLike, **options: Any) -> int: ...
def sender_send_audio(sender: TrackSender, data: BytesLike, **options: Any) -> int: ...
def recover_channel(session: Session, track: Track, key_unit: BytesLike) -> TrackSender: ...

def activate_track(
    session: Session, surface: Surface, track: Track, *, required_milestone: int = ...
) -> int: ...
def activate_tracks(session: Session, surface: Surface, bindings: Sequence[Config]) -> int: ...
def wait_track(
    session: Session,
    track: Track,
    condition: int,
    value: Optional[int] = ...,
    timeout_us: int = ...,
) -> Dict[str, Any]: ...

def play(
    session: Session,
    track: Track,
    start_pts_us: int,
    minimum_buffer_us: int,
    maximum_latency_us: int,
) -> None: ...
def pause(session: Session, track: Track) -> None: ...
def set_audio_gain(session: Session, track: Track, raw: int) -> None: ...
def flush(session: Session, track: Track, new_epoch: int) -> None: ...
def drain(session: Session, track: Track) -> None: ...

def create_node(session: Session, surface: Surface, config: Config) -> Dict[str, Any]: ...
def update_node(session: Session, surface: Surface, config: Config) -> Dict[str, Any]: ...
def place_terminal_surface(
    session: Session,
    surface: Surface,
    *,
    node_id: int,
    x: int = ...,
    y: int = ...,
    width: int,
    height: int,
    text_layer: int = ...,
) -> Tuple[int, int]: ...
def delete_node(session: Session, context_id: int, node_id: int) -> Tuple[int, int]: ...
def anchor_marker(session: Session, context_id: int, anchor_id: int) -> str: ...
def conpty_anchor_marker(session: Session, context_id: int, anchor_id: int) -> str: ...
def query_anchor(session: Session, context_id: int, anchor_id: int) -> Dict[str, Any]: ...

def open_input_lane(session: Session, lane_generation: int) -> InputLane: ...
def close_input_lane(lane: InputLane) -> None: ...
def set_input_binding(lane: InputLane, config: Config) -> Dict[str, Any]: ...
def lane_take_event(lane: InputLane) -> Optional[Dict[str, Any]]: ...
def lane_wait_event(lane: InputLane, *, timeout_us: int = ...) -> Optional[Dict[str, Any]]: ...

def create_context(session: Session, **options: Any) -> Dict[str, Any]: ...
def create_session_lease(session: Session, **options: Any) -> Dict[str, Any]: ...
def revoke_session_lease(session: Session, context_id: int, lease_id: int) -> None: ...
def set_observation(session: Session, mask: int) -> None: ...
def prepare_resume(session: Session) -> Dict[str, int]: ...
def query_session(session: Session) -> Dict[int, Any]: ...

def set_file_drop_binding(session: Session, config: Config) -> Dict[str, Any]: ...
def accept_file_drop(
    session: Session,
    drop: Config,
    transfer_id: int,
    transfer_generation: int,
    maximum_record_body: int,
    initial_maximum_body_bytes: int,
    initial_maximum_records: int,
) -> Dict[str, Any]: ...
def cancel_file_drop(session: Session, drop: Config, reason: int) -> None: ...
def advance_file_transfer(session: Session, config: Config) -> Dict[str, Any]: ...
def query_file_drop(session: Session, drop_id: int) -> Dict[str, Any]: ...
def open_incoming_file_transfer(session: Session, config: Config) -> IncomingFileTransfer: ...
def read_transfer_event(transfer: IncomingFileTransfer) -> Dict[str, Any]: ...
def set_transfer_read_deadline(
    transfer: IncomingFileTransfer, timeout_us: Optional[int]
) -> None: ...
def grant_transfer(
    transfer: IncomingFileTransfer, maximum_body_bytes: int, maximum_records: int
) -> None: ...
def send_transfer_result(transfer: IncomingFileTransfer, config: Config) -> None: ...
def abort_transfer(transfer: IncomingFileTransfer, reason: int) -> None: ...

def pane_show_encoded_image(
    pane: PaneSession, encoded: bytes, options: Optional[Config] = ...
) -> None: ...
def pane_show_rgba(
    pane: PaneSession, width: int, height: int, rgba: bytes, options: Optional[Config] = ...
) -> None: ...
def pane_clear(pane: PaneSession) -> None: ...
def pane_close(pane: PaneSession) -> None: ...

def establish_desktop(
    session: Session, surface: Config, video: Config, audio: Optional[Config] = ...
) -> DesktopSession: ...
def desktop_video_track(desktop: DesktopSession) -> Track: ...
def desktop_audio_track(desktop: DesktopSession) -> Optional[Track]: ...
def desktop_send_video(desktop: DesktopSession, data: bytes, **options: Any) -> int: ...
def desktop_send_audio(
    desktop: DesktopSession, data: bytes, packet_id: int, pts_us: int, duration_us: int
) -> int: ...
def desktop_activate_slots(desktop: DesktopSession) -> None: ...
def desktop_close(desktop: DesktopSession) -> None: ...

def presenter_start(
    endpoint: str, desktop: Optional[Tuple[int, int]] = ..., retained_bytes: Optional[int] = ...
) -> Presenter: ...
def presenter_close(presenter: Presenter) -> None: ...
def presenter_issue_pane_capability(presenter: Presenter, pane: int) -> str: ...
def presenter_revoke_pane(presenter: Presenter, pane: int) -> None: ...
def presenter_update_metrics(
    presenter: Presenter, pane: int, columns: int, rows: int, cell_width: int, cell_height: int
) -> None: ...
def presenter_wait_for_media(presenter: Presenter, pane: int, timeout_ms: int) -> bool: ...
def presenter_capture_pane(presenter: Presenter, pane: int, viewport_offset: int) -> Dict[str, Any]: ...
def presenter_pane_media_summary(presenter: Presenter, pane: int) -> Dict[str, Any]: ...
def presenter_queue_microphone(
    presenter: Presenter, source: Config, generation: int, bytes: bytes
) -> bool: ...
def presenter_revoke_microphones(presenter: Presenter) -> None: ...
def presenter_notify_capabilities_changed(presenter: Presenter, reason_mask: int) -> int: ...
def presenter_update_desktop_target(
    presenter: Presenter, pane: int, width: int, height: int, reason_mask: int
) -> int: ...
def presenter_observe_marker(
    presenter: Presenter, pane: int, value: str, row: int, column: int, alternate: bool
) -> None: ...
def presenter_scroll_anchors(
    presenter: Presenter, pane: int, lines: int, alternate: bool
) -> None: ...
def presenter_clear_anchors(presenter: Presenter, pane: int, alternate: bool) -> None: ...
def presenter_set_alternate_screen(
    presenter: Presenter, pane: int, alternate: bool
) -> None: ...
def presenter_pane_for_source(presenter: Presenter, source: Config) -> Optional[int]: ...
def presenter_projection_revision(presenter: Presenter) -> int: ...
def presenter_request_keyframe(
    presenter: Presenter, source: Config, minimum_epoch: Optional[int], reason: int
) -> str: ...
def presenter_request_full_frames(
    presenter: Presenter, sources: Sequence[Config], reason: int
) -> None: ...
def presenter_apply_outer_position(
    presenter: Presenter, source: Config, position: Config
) -> None: ...
def presenter_apply_outer_playback(
    presenter: Presenter,
    source: Config,
    decoder_reset_serial: int,
    state_value: int,
    eos_state: int,
) -> None: ...
def presenter_announce_media_resource(
    presenter: Presenter, source: Config, pinned: bool
) -> str: ...
def presenter_describe_media_resource(presenter: Presenter, id: str) -> Dict[str, Any]: ...
def presenter_release_media_resource(presenter: Presenter, id: str) -> bool: ...
